version: 0.2
phases:
  install:
    runtime-version:
      nodejs: 16
    commands:
      - echo "installing dependencies.."
      - npm install
      - npm install -g @angular/cli@14.2.9
  build:
     commands:
       - echo "Building angular project.."
       - ng build --configuration production
  post_build:
      commands:
         - echo "updating files in s3 bucket..."
         - aws s3 sync dist/awsproject/ s3://awsproject-2023 --delete